<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //ALUMNOS NUEVO INGRESO
         DB::table('users')->insert([
            'id' => 'R161315426',
            'role' => 'ROLE_STUDENT',
            'name' => 'LEAH',
            'last_name' => 'CARREÓN',
            'second_last_name' => 'VILLALOBOS',
            'gender' => 'MUJER',
            'birthday' => '1998-05-20',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => '2019-08-30',
            'insurance' => '',
            'email' => 'LEAHCARRE@GMAIL.COM',
            'phone' => '4491238752',
            'outdoor_number' => 430,
            'interior_number' => '',
            'street' => 'REAL DE AGUASCALIENTES',
            'locality' => '',
            'neighborhood' => 'COL. CENTRO',
            'postal_code' => 20150,
            'current_township_id' => '2429',
            'birthday_place' => '1',
            'rfc' => '',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);

         DB::table('users')->insert([
            'id' => 'R161364876',
            'role' => 'ROLE_STUDENT',
            'name' => 'EDGAR',
            'last_name' => 'ZACARÍAS',
            'second_last_name' => 'NIETO',
            'gender' => 'HOMBRE',
            'birthday' => '1998-12-12',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => '2019-08-20',
            'insurance' => '',
            'email' => 'EDGARZACARI@GMAIL.COM',
            'phone' => '4961257866',
            'outdoor_number' => 110,
            'interior_number' => '',
            'street' => 'IGNACIO ALLENDE',
            'locality' => '',
            'neighborhood' => 'COL. MINERA',
            'postal_code' => 33000,
            'current_township_id' => '2430',
            'birthday_place' => '32',
            'rfc' => '',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);

         DB::table('users')->insert([
            'id' => 'R161364875',
            'role' => 'ROLE_STUDENT',
            'name' => 'EDGAR',
            'last_name' => 'ZACARÍAS',
            'second_last_name' => 'NIETO',
            'gender' => 'HOMBRE',
            'birthday' => '1998-12-12',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => '2019-08-20',
            'insurance' => '',
            'email' => 'EDGARZACARI@GMAIL.COM',
            'phone' => '4961257866',
            'outdoor_number' => 110,
            'interior_number' => '',
            'street' => 'IGNACIO ALLENDE',
            'locality' => '',
            'neighborhood' => 'COL. MINERA',
            'postal_code' => 33000,
            'current_township_id' => '2430',
            'birthday_place' => '32',
            'rfc' => '',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);

        DB::table('users')->insert([
            'id' => 'R161324168',
            'role' => 'ROLE_STUDENT',
            'name' => 'CARLOS',
            'last_name' => 'AMADOR',
            'second_last_name' => 'CAÑADA',
            'gender' => 'HOMBRE',
            'birthday' => '1998-02-14',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => '2019-08-19',
            'insurance' => '',
            'email' => 'CARLOSAMA@GMAIL.COM',
            'phone' => '4961485784',
            'outdoor_number' => 150,
            'interior_number' => '',
            'street' => 'TORRES QUINTERO',
            'locality' => '',
            'neighborhood' => 'COL. ARENAS',
            'postal_code' => 34000,
            'current_township_id' => '2',
            'birthday_place' => '1',
            'rfc' => '',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        
        //ALUMNOS ITI
        DB::table('users')->insert([
            'id' => 'R161306021',
            'role' => 'ROLE_STUDENT',
            'name' => 'JOSÉ FRANCISCO',
            'last_name' => 'AMADOR',
            'second_last_name' => 'RODRÍGUEZ',
            'gender' => 'HOMBRE',
            'birthday' => '1998-08-20',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => '2019-08-18',
            'insurance' => '',
            'email' => 'franciscoamador@gmail.com',
            'phone' => '4964854465',
            'outdoor_number' => 8,
            'interior_number' => '',
            'street' => 'TIJERA',
            'locality' => '',
            'neighborhood' => 'COL. BUENAVISTA',
            'postal_code' => 34000,
            'current_township_id' => '2441',
            'birthday_place' => '1',
            'rfc' => '',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);

        DB::table('users')->insert([
            'id' => 'R161306068',
            'role' => 'ROLE_STUDENT',
            'name' => 'ABEL',
            'last_name' => 'ARENAS',
            'second_last_name' => 'DUEÑAS',
            'gender' => 'HOMBRE',
            'birthday' => '1998-01-15',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => '2019-08-19',
            'insurance' => '',
            'email' => 'abelarenas@gmail.com',
            'phone' => '4961365847',
            'outdoor_number' => 310,
            'interior_number' => '',
            'street' => 'PERNSADOR MEXICANO',
            'locality' => '',
            'neighborhood' => 'COL. CENTRO',
            'postal_code' => 34000,
            'current_township_id' => '2429',
            'birthday_place' => '1',
            'rfc' => '',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);

        DB::table('users')->insert([
            'id' => 'R160306165',
            'role' => 'ROLE_STUDENT',
            'name' => 'HÉCTOR RAMÓN',
            'last_name' => 'GUTÍERREZ',
            'second_last_name' => 'ZAMBRANO',
            'gender' => 'HOMBRE',
            'birthday' => '1998-11-30',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => '2019-08-24',
            'insurance' => '',
            'email' => 'hectorgutierrez@gmail.com',
            'phone' => '4651548726',
            'outdoor_number' => 459,
            'interior_number' => '',
            'street' => 'VILLANUEVA',
            'locality' => '',
            'neighborhood' => 'COL. ANIMAS',
            'postal_code' => 35000,
            'current_township_id' => '6',
            'birthday_place' => '1',
            'rfc' => '',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);

        DB::table('users')->insert([
            'id' => 'R162506099',
            'role' => 'ROLE_STUDENT',
            'name' => 'ALFREDO',
            'last_name' => 'MACÍAS',
            'second_last_name' => 'MARTÍNEZ',
            'gender' => 'HOMBRE',
            'birthday' => '1998-03-09',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => '2019-11-02',
            'insurance' => '',
            'email' => 'alfredomacias@gmail.com',
            'phone' => '4651290412',
            'outdoor_number' => 110,
            'interior_number' => '',
            'street' => 'LUIS SANDOVAL',
            'locality' => '',
            'neighborhood' => 'COL. PINOS',
            'postal_code' => 33000,
            'current_township_id' => '1',
            'birthday_place' => '1',
            'rfc' => '',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);

        DB::table('users')->insert([
            'id' => 'R161305933',
            'role' => 'ROLE_STUDENT',
            'name' => 'GEMA',
            'last_name' => 'MORÁN',
            'second_last_name' => 'VILLALOBOS',
            'gender' => 'MUJER',
            'birthday' => '1998-04-12',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => '2019-08-22',
            'insurance' => '',
            'email' => 'gemamoran35@gmail.com',
            'phone' => '4651038729',
            'outdoor_number' => 200,
            'interior_number' => '',
            'street' => 'REAL DE ZACATECAS',
            'locality' => '',
            'neighborhood' => 'COL. SANTA ISABEL',
            'postal_code' => 35000,
            'current_township_id' => '6',
            'birthday_place' => '1',
            'rfc' => '',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);

        //CAJERO
        DB::table('users')->insert([
            'id' => 'R100000000',
            'role' => 'ROLE_CASHIER',
            'name' => 'MARÍA',
            'last_name' => 'CASTILLO',
            'second_last_name' => 'ORTIZ',
            'gender' => 'MUJER',
            'birthday' => '1985-07-11',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'MARIACASTI@GMAIL.COM',
            'phone' => '4491261864',
            'outdoor_number' => 950,
            'interior_number' => '',
            'street' => 'REVOLUCIÓN',
            'locality' => '',
            'neighborhood' => 'COL. PETROLEOS',
            'postal_code' => 36000,
            'current_township_id' => '1',
            'birthday_place' => '1',
            'rfc' => 'CAOM8597112G2',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        //MAESTROS
        DB::table('users')->insert([
            'id' => '11111',
            'role' => 'ROLE_TEACHER',
            'name' => 'ROCÍO',
            'last_name' => 'MARTÍNEZ',
            'second_last_name' => 'RODRÍGUEZ',
            'gender' => 'MUJER',
            'birthday' => '1976-02-26',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'ROCIORODRI@GMAIL.COM',
            'phone' => '4491367452',
            'outdoor_number' => 640,
            'interior_number' => '',
            'street' => 'NIÑOS HEROES',
            'locality' => '',
            'neighborhood' => 'COL. ALMA',
            'postal_code' => 36000,
            'current_township_id' => '1',
            'birthday_place' => '1',
            'rfc' => 'MARR760226HC6',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        DB::table('users')->insert([
            'id' => '11112',
            'role' => 'ROLE_TEACHER',
            'name' => 'GRACIELA',
            'last_name' => 'CHÁVEZ',
            'second_last_name' => 'MATAMOROS',
            'gender' => 'MUJER',
            'birthday' => '1980-04-15',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'GRACIELACHA@GMAIL.COM',
            'phone' => '4491168359',
            'outdoor_number' => 460,
            'interior_number' => '',
            'street' => '5 DE MAYO',
            'locality' => '',
            'neighborhood' => 'COL. ARENAS',
            'postal_code' => 98000,
            'current_township_id' => '2429',
            'birthday_place' => '2',
            'rfc' => 'CHMG800415GB4',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        DB::table('users')->insert([
            'id' => '11113',
            'role' => 'ROLE_TEACHER',
            'name' => 'JORGE',
            'last_name' => 'VALADEZ',
            'second_last_name' => 'GOMEZ',
            'gender' => 'HOMBRE',
            'birthday' => '1960-05-04',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'JORGEVAL@GMAIL.COM',
            'phone' => '4921549814',
            'outdoor_number' => 255,
            'interior_number' => '',
            'street' => 'FERROCARRIL',
            'locality' => '',
            'neighborhood' => 'COL. OBRERA',
            'postal_code' => 36000,
            'current_township_id' => '1',
            'birthday_place' => '1',
            'rfc' => 'VAGR6005044FC',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        DB::table('users')->insert([
            'id' => '11114',
            'role' => 'ROLE_TEACHER',
            'name' => 'DANIEL',
            'last_name' => 'GARCÍA',
            'second_last_name' => 'LUÉVANO',
            'gender' => 'HOMBRE',
            'birthday' => '1990-08-26',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'DANIELGAR@GMAIL.COM',
            'phone' => '4491464656',
            'outdoor_number' => 40,
            'interior_number' => '',
            'street' => 'OJOCALIENTE',
            'locality' => '',
            'neighborhood' => 'COL. NACOZARI',
            'postal_code' => 36400,
            'current_township_id' => '1',
            'birthday_place' => '1',
            'rfc' => 'GALD9008267FF',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        DB::table('users')->insert([
            'id' => '11115',
            'role' => 'ROLE_TEACHER',
            'name' => 'ALEJANDRO',
            'last_name' => 'CARREÓN',
            'second_last_name' => 'CASTAÑEDA',
            'gender' => 'HOMBRE',
            'birthday' => '1986-06-18',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'ALEJANDROCARR@GMAIL.COM',
            'phone' => '4491442423',
            'outdoor_number' => 375,
            'interior_number' => '',
            'street' => 'IGNACIO ALLENDE',
            'locality' => '',
            'neighborhood' => 'COL. VEGA',
            'postal_code' => 93300,
            'current_township_id' => '2430',
            'birthday_place' => '3',
            'rfc' => 'CACA8606182BV',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        DB::table('users')->insert([
            'id' => '11116',
            'role' => 'ROLE_TEACHER',
            'name' => 'JOSUÉ',
            'last_name' => 'ZAPATA',
            'second_last_name' => 'CRUZ',
            'gender' => 'HOMBRE',
            'birthday' => '1994-01-03',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'JOSUEZAPA@GMAIL.COM',
            'phone' => '4654875154',
            'outdoor_number' => 777,
            'interior_number' => '',
            'street' => 'DON QUIJOTE',
            'locality' => '',
            'neighborhood' => 'COL. TORRES',
            'postal_code' => 93300,
            'current_township_id' => '2430',
            'birthday_place' => '4',
            'rfc' => 'ZACJ9401038QF',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        DB::table('users')->insert([
            'id' => '11117',
            'role' => 'ROLE_TEACHER',
            'name' => 'GALILEA',
            'last_name' => 'DE LEÓN',
            'second_last_name' => 'ESPERANZA',
            'gender' => 'MUJER',
            'birthday' => '1985-12-31',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'GALILEADE@GMAIL.COM',
            'phone' => '4491129752',
            'outdoor_number' => 832,
            'interior_number' => '',
            'street' => 'INDEPENDENCIA',
            'locality' => '',
            'neighborhood' => 'COL. MINERA',
            'postal_code' => 33000,
            'current_township_id' => '1',
            'birthday_place' => '1',
            'rfc' => 'DEEG851231GG3',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        DB::table('users')->insert([
            'id' => '11118',
            'role' => 'ROLE_TEACHER',
            'name' => 'FELIPE',
            'last_name' => 'TOSCAREÑO',
            'second_last_name' => 'CHEVERRIA',
            'gender' => 'HOMBRE',
            'birthday' => '1950-03-10',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'FELIPETOSCA@GMAIL.COM',
            'phone' => '4491101512',
            'outdoor_number' => 565,
            'interior_number' => '',
            'street' => 'VENUSTIANO CARRANZA',
            'locality' => '',
            'neighborhood' => 'COL. CENTRO',
            'postal_code' => 93000,
            'current_township_id' => '2430',
            'birthday_place' => '1',
            'rfc' => 'TOCF500310TT4',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
        DB::table('users')->insert([
            'id' => '11119',
            'role' => 'ROLE_TEACHER',
            'name' => 'BLANCA',
            'last_name' => 'MARTÍNEZ',
            'second_last_name' => 'RUVALCABA',
            'gender' => 'MUJER',
            'birthday' => '1993-09-18',
            'nationality' => 'MEXICANA',
            'curp' => '',
            'admission_date' => now(),
            'insurance' => '',
            'email' => 'BLANCAMAR@GMAIL.COM',
            'phone' => '4491139634',
            'outdoor_number' => 130,
            'interior_number' => '',
            'street' => 'JUAN ALDAMA',
            'locality' => '',
            'neighborhood' => 'COL. PIÑEDA',
            'postal_code' => 36000,
            'current_township_id' => '1',
            'birthday_place' => '1',
            'rfc' => 'MARB930918HY8',
            'status' => 'ACTIVO',
            'password' => bcrypt('PASSWORD')
        ]);
    }
}
